# --- Metadata for the App UI ---
building_info:
  project_name: "10-Story Wall-Frame Building"
  project_owner: "SURA"
  fundamental_period_x: "1.0 s"
  fundamental_period_y: "1.3 s"
  number_of_instruments: 3

# --- NEW: Earthquake Event Metadata ---
event_metadata:
  event_name: "Paratebueno-Cundinamarca"
  date_time: "2025-07-31 10:30:00 UTC"
  epicentral_distance_km: 250.0
  site_location: "Medellín, Antioquia"
  max_recorded_acceleration_g: 0.45

# --- Parameters for PullOver Analysis ---
analysis_setup:
  instrumented_nodes: [504 , 508 ]
  master_nodes: [501, 502, 503, 504, 505, 506, 507, 508, 509, 510]
  dt: 0.02
  npts: 4502

# --- Parameters for Damage Detection ---
damage_detection:
  yield_parameters:
    column:
      My_yield_x: 1000000.0
      Mz_yield_x: 1000000.0
      phi_yield_y: 0.05
      phi_yield_z: 0.05
    beam_X:
      My_yield_x: 612000.0
      Mz_yield_x: 1650000.0
      phi_yield_y: 0.05
      phi_yield_z: 0.05
    beam_Y:
      My_yield_y: 612000.0
      Mz_yield_y: 1650000.0
      phi_yield_y: 0.05
      phi_yield_z: 0.05

  element_ranges:
    - { type: column, start_ele: 10006, end_ele: 10021 }
    - { type: column, start_ele: 10046, end_ele: 10049 }
    - { type: column, start_ele: 10056, end_ele: 10059 }
    - { type: column, start_ele: 10066, end_ele: 10069 }
    - { type: column, start_ele: 10076, end_ele: 10079 }
    - { type: column, start_ele: 10086, end_ele: 10089 }
    - { type: column, start_ele: 10096, end_ele: 10099 }
    - { type: beam_X, start_ele: 10022, end_ele: 10037 }
    - { type: beam_X, start_ele: 10050, end_ele: 10053 }
    - { type: beam_X, start_ele: 10060, end_ele: 10063 }
    - { type: beam_X, start_ele: 10070, end_ele: 10073 }
    - { type: beam_X, start_ele: 10080, end_ele: 10083 }
    - { type: beam_X, start_ele: 10090, end_ele: 10093 }
    - { type: beam_X, start_ele: 10100, end_ele: 10103 }
    - { type: beam_Y, start_ele: 10038, end_ele: 10045 }
    - { type: beam_Y, start_ele: 10054, end_ele: 10055 }
    - { type: beam_Y, start_ele: 10064, end_ele: 10065 }
    - { type: beam_Y, start_ele: 10074, end_ele: 10075 }
    - { type: beam_Y, start_ele: 10084, end_ele: 10085 }
    - { type: beam_Y, start_ele: 10094, end_ele: 10095 }
    - { type: beam_Y, start_ele: 10104, end_ele: 10105 }

  base_cost_per_element: 15000.0
